# Generated by Django 4.2.26 on 2025-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0002_alter_productsize_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
