# Generated by Django 4.2.26 on 2025-11-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0004_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ítem de Pedido', 'verbose_name_plural': 'Ítems de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productbreadcrumb',
            options={'ordering': ['position'], 'verbose_name': 'Miga de Pan', 'verbose_name_plural': 'Migas de Pan'},
        ),
        migrations.AlterModelOptions(
            name='productcare',
            options={'verbose_name': 'Cuidado de Producto', 'verbose_name_plural': 'Cuidados de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalles de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Talla de Producto', 'verbose_name_plural': 'Tallas de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productspec',
            options={'verbose_name': 'Especificación de Producto', 'verbose_name_plural': 'Especificaciones de Productos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('Online', 'Online'), ('Tienda', 'Tienda')], default='Online', max_length=10, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='appOnichan.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appOnichan.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(help_text='Precio unitario en CLP', verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='appOnichan.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=300, verbose_name='URL Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Precio en CLP (entero)', verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productbreadcrumb',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbreadcrumb',
            name='label',
            field=models.CharField(max_length=60, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='productbreadcrumb',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='productbreadcrumb',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productcare',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productcare',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Cuidado'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='capacity_l',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (L)'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='descuento_pct',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje Descuento'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='envio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Envío'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='llega',
            field=models.CharField(blank=True, max_length=120, verbose_name='Llega'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Calificaciones'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=120, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='label',
            field=models.CharField(max_length=20, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='appOnichan.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Especificación'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='apponichan_category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='apponichan_customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='apponichan_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='apponichan_orderitem',
        ),
        migrations.AlterModelTable(
            name='product',
            table='apponichan_product',
        ),
        migrations.AlterModelTable(
            name='productbreadcrumb',
            table='apponichan_productbreadcrumb',
        ),
        migrations.AlterModelTable(
            name='productcare',
            table='apponichan_productcare',
        ),
        migrations.AlterModelTable(
            name='productdetail',
            table='apponichan_productdetail',
        ),
        migrations.AlterModelTable(
            name='productsize',
            table='apponichan_productsize',
        ),
        migrations.AlterModelTable(
            name='productspec',
            table='apponichan_productspec',
        ),
    ]
