# Generated by Django 4.2.26 on 2025-11-25 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOnichan', '0006_order_contact_email_order_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
