# Generated by Django 4.2.26 on 2025-11-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0008_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Porcentaje entre 1 y 100', verbose_name='Porcentaje de Descuento')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 para ilimitado', verbose_name='Límite de Uso')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
    ]
