# Generated by Django 4.2.26 on 2025-11-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote / Grupo'),
        ),
        migrations.CreateModel(
            name='BulkOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Oferta')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='Porcentaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('products', models.ManyToManyField(related_name='bulk_offers', to='appOnichan.product', verbose_name='Productos Afectados')),
            ],
            options={
                'verbose_name': 'Oferta Masiva',
                'verbose_name_plural': 'Ofertas Masivas',
            },
        ),
    ]
