# Generated by Django 4.2.26 on 2025-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0010_coupon_batch_name_bulkoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento Aplicado'),
        ),
    ]
