# Generated by Django 4.2.26 on 2025-11-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0011_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, verbose_name='Tiene Tallas'),
        ),
    ]
