# Generated by Django 4.2.26 on 2025-11-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0012_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Multitienda', max_length=200, verbose_name='Nombre del Sitio')),
                ('welcome_message', models.CharField(default='Descubre lo último en tendencias con un estilo único.', max_length=200, verbose_name='Mensaje de Bienvenida')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Umbral de Stock Bajo')),
                ('contact_email', models.EmailField(default='contacto@multitienda.cl', max_length=254, verbose_name='Email de Contacto')),
                ('items_per_page', models.PositiveIntegerField(default=12, verbose_name='Productos por página')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
