# Generated by Django 4.2.26 on 2025-11-27 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOnichan', '0013_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Canje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Costo en Puntos')),
                ('reward_type', models.CharField(choices=[('COUPON', 'Cupón de Descuento'), ('PRODUCT', 'Producto Gratis')], default='PRODUCT', max_length=20, verbose_name='Tipo de Recompensa')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='URL Imagen (Opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOnichan.coupon', verbose_name='Cupón Asociado')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOnichan.product', verbose_name='Producto a Canjear')),
            ],
            options={
                'verbose_name': 'Recompensa por Puntos',
                'verbose_name_plural': 'Recompensas por Puntos',
            },
        ),
        migrations.CreateModel(
            name='RedemptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Puntos Gastados')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Canje')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOnichan.pointreward', verbose_name='Recompensa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Canje',
                'verbose_name_plural': 'Historial de Canjes',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
