# Generated by Django 4.2.26 on 2025-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0014_pointreward_redemptionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointreward',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta'),
        ),
    ]
