# Generated by Django 4.2.24 on 2025-11-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOnichan', '0015_pointreward_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Adquisición')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='appOnichan.coupon', verbose_name='Cupón')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cupón de Usuario',
                'verbose_name_plural': 'Cupones de Usuarios',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
