# Generated by Django 4.2.26 on 2025-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0016_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointreward',
            name='coupon_batch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote de Cupones'),
        ),
    ]
