# Generated by Django 4.2.26 on 2025-11-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0017_pointreward_coupon_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointreward',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Disponible'),
        ),
    ]
