# Generated by Django 4.2.26 on 2025-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0018_pointreward_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre Destinatario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('En camino', 'En camino'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Fallido', 'Fallido'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado'),
        ),
    ]
