# Generated by Django 4.2.24 on 2025-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOnichan', '0019_order_recipient_name_alter_order_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reward',
            field=models.BooleanField(default=False, verbose_name='Es Recompensa'),
        ),
    ]
