# Generated by Django 4.2.24 on 2025-12-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOnichan', '0022_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Template')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto del Correo (Default)')),
                ('content_html', models.TextField(blank=True, verbose_name='Contenido HTML')),
                ('design_json', models.JSONField(blank=True, null=True, verbose_name='Diseño (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Campaña')),
                ('subject', models.CharField(blank=True, help_text='Si se deja vacío usa el del template', max_length=200)),
                ('include_coupon', models.BooleanField(default=False, verbose_name='¿Incluir Cupón Personalizado?')),
                ('coupon_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='% Descuento')),
                ('coupon_valid_days', models.IntegerField(default=7, verbose_name='Días de validez')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sent', 'Enviada')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appOnichan.marketingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOnichan.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
